pr-close.yml

For visibility use a symbolic link to "put" pr-close in the repo root.

feat: alias from workflows to root

---

.github/workflows/.pr-close.yml
.github/workflows/.pr-validate.yml
.github/workflows/pr-open.yml
pr-validate.yml

---
- [Frontend](https://quickstart-openshift-helpers-4-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-4-frontend.apps.silver.devops.gov.bc.ca/api)

feat: pr-validate

---

.github/codeowners

---
- [Frontend](https://quickstart-openshift-helpers-5-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-5-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): codeowners

---

.github/workflows/.pr-validate.yml

---
- [Frontend](https://quickstart-openshift-helpers-7-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-7-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): rename job

---

.github/workflows/.pr-validate.yml
.github/workflows/pr-open.yml

Most of our workflows and actions have problems with forks.  This allow blocking them and kicking up a warning.
---
- [Frontend](https://quickstart-openshift-helpers-8-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-8-frontend.apps.silver.devops.gov.bc.ca/api)

feat: block forks

---

.github/workflows/.pr-close.yml
.github/workflows/.pr-validate.yml

Simplify jobs so that workflows can more easily check pass/fail.
---
- [Frontend](https://quickstart-openshift-helpers-9-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-9-frontend.apps.silver.devops.gov.bc.ca/api)

chore: reduce validation to one job

---

charts/app/templates/secret.yaml

---
- [Frontend](https://quickstart-openshift-helpers-20-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-20-frontend.apps.silver.devops.gov.bc.ca/api)

fix: helm db secrets overwritten

---

.github/workflows/.deployer.yml

---
- [Frontend](https://quickstart-openshift-helpers-23-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-23-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): only interrupt Helm deployments on PRs

---

.github/workflows/.pr-close.yml

Slight code reduction.  At least feels a little smarter.
---
- [Frontend](https://quickstart-openshift-helpers-25-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-25-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): use common login for oc or helm cleanup

---

.github/workflows/.deployer.yml

When Helm triggers don't fire it's running exit 0, but the following steps, including deployment, are still happening.
---
- [Frontend](https://quickstart-openshift-helpers-28-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-28-frontend.apps.silver.devops.gov.bc.ca/api)

fix: Helm triggers

---

.github/workflows/.deployer.yml
.github/workflows/.pr-close.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-helpers-29-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-29-frontend.apps.silver.devops.gov.bc.ca/api)

fix(ci): promotions happening at wrong times

---

.gitignore
csr_generator.sh

---
- [Frontend](https://quickstart-openshift-helpers-31-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-31-frontend.apps.silver.devops.gov.bc.ca/api)

feat(ci): move csr_generator from qsos

---

.github/workflows/.pr-close.yml

---
- [Frontend](https://quickstart-openshift-helpers-34-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-34-frontend.apps.silver.devops.gov.bc.ca/api)

fix(ci): promotions not always triggering

---

cert-setup/csr_generator.sh
cert-setup/install_cert.sh

---
- [Frontend](https://quickstart-openshift-helpers-39-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-39-frontend.apps.silver.devops.gov.bc.ca/api)

fix: route collisions

---

.github/workflows/.deployer.yml
.github/workflows/pr-open.yml

Resolves https://github.com/bcgov/quickstart-openshift/issues/1921
---
- [Frontend](https://quickstart-openshift-helpers-41-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-41-frontend.apps.silver.devops.gov.bc.ca/api)
---
- [Frontend](https://quickstart-openshift-helpers-41-frontend.apps.silver.devops.gov.bc. …

fix: trigger outputs

---

.github/workflows/.deployer.yml

Closes https://github.com/bcgov/quickstart-openshift/issues/2005
---
- [Frontend](https://quickstart-openshift-helpers-45-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-45-frontend.apps.silver.devops.gov.bc.ca/api)

feat: deployer atomic param

---

README.md
cert-setup/README.md
cert-setup/csr_generator.sh
cert-setup/install_cert.sh

SSL scripts
* add support for paths
* replace checks with something that doesn't fail on MacOS
Documentation

chore(ci): cert routes and checks

---

cert-setup/csr_generator.sh
cert-setup/install_cert.sh

- echo the new route
- provide a prompt to visit the new route
- echo available services for user selection
- stopped clobbering the PATH variable

feat: cert setup features, fixes

---

.github/codeowners
.github/workflows/.pr-close.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-helpers-57-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-57-frontend.apps.silver.devops.gov.bc.ca/api)

chore: compare digest with retry before fail

---

.github/workflows/.pr-close.yml

---
- [Frontend](https://quickstart-openshift-helpers-58-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-58-frontend.apps.silver.devops.gov.bc.ca/api)

feat: Added logging to sha compare for more verbose logging

---

.github/workflows/.pr-validate.yml

---
- [Frontend](https://quickstart-openshift-helpers-59-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-59-frontend.apps.silver.devops.gov.bc.ca/api)

chore: update pr description action

---

.github/workflows/.deployer.yml
.github/workflows/.pr-close.yml

---
- [Frontend](https://quickstart-openshift-helpers-80-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-80-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): gh runner oc changes

---

.github/workflows/.deployer.yml

---
- [Frontend](https://quickstart-openshift-helpers-82-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-82-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): use latest v4 oc runner

---

.github/workflows/.pr-validate.yml

Reverts bcgov/quickstart-openshift-helpers#85

Revert "chore(deps): update bcgov-nr/action-pr-description-add action to v1.2.0"

---

.github/workflows/.pr-close.yml

---
- [Frontend](https://quickstart-openshift-helpers-87-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-87-frontend.apps.silver.devops.gov.bc.ca/api)

feat: add param for github environments

---

.github/workflows/.deployer.yml

---
- [Frontend](https://quickstart-openshift-helpers-91-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-91-frontend.apps.silver.devops.gov.bc.ca/api)

fix: token request api warning

---

.github/workflows/.deployer.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-helpers-92-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-92-frontend.apps.silver.devops.gov.bc.ca/api)

fix: get PR only when the tag is not provided.

---

.github/workflows/.pr-close.yml

---
- [Frontend](https://quickstart-openshift-helpers-95-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-95-frontend.apps.silver.devops.gov.bc.ca/api)

feat: param to override repo name in template cleanup

---

.github/workflows/.deployer.yml
.github/workflows/.pr-validate.yml
.github/workflows/builds.yml

---
- [Frontend](https://quickstart-openshift-helpers-115-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-115-frontend.apps.silver.devops.gov.bc.ca/api)

chore: transfer actions to bcgov org

---

.github/workflows/.deployer.yml
.github/workflows/.pr-close.yml

---
- [Frontend](https://quickstart-openshift-helpers-116-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-116-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): remove JS handling from workflow conditionals

---

.github/workflows/.deployer.yml
.github/workflows/.pr-close.yml
.github/workflows/.pr-validate.yml
.github/workflows/.schema-spy.yml
.github/workflows/builds.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-helpers-119-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-119-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): use GH runner ubuntu-24.04

---

.github/workflows/.deployer.yml
.github/workflows/.pr-close.yml

---
- [Frontend](https://quickstart-openshift-helpers-118-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-118-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): keep using action-oc-runner

---

.github/workflows/csr-generator.yml
.github/workflows/pr-open.yml
.gitignore
cert-setup/csr_generator.sh

---
- [Frontend](https://quickstart-openshift-helpers-125-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-125-frontend.apps.silver.devops.gov.bc.ca/api)

feat: add a way to pass existing key while generating csr

---

.github/workflows/.pr-close.yml

---
- [Frontend](https://quickstart-openshift-helpers-131-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-131-frontend.apps.silver.devops.gov.bc.ca/api)

fix: commands param

---

.github/workflows/.deployer-db.yml
.github/workflows/.deployer.yml
.github/workflows/pr-open.yml
cert-setup/install_cert.sh
charts/crunchy/Chart.yaml
charts/crunchy/templates/PostgresCluster.yaml
charts/crunchy/templates/_helpers.tpl
charts/crunchy/templates/knp.yaml
charts/crunchy/templates/secret.yaml
charts/crunchy/values.yaml

---
- [Frontend](https://quickstart-openshift-helpers-135-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-135-frontend.apps.silver.devops.gov.bc.ca/api)

feat: crunchy deployer workflow

---

.github/workflows/.deployer-db.yml
.github/workflows/.deployer.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-helpers-139-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-139-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): fix merge problem

---

.github/workflows/.deployer-db.yml

---
- [Frontend](https://quickstart-openshift-helpers-141-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-141-frontend.apps.silver.devops.gov.bc.ca/api)

fix: manually specify crunchy branch

---

actions/crunchy/README.md

---
- [Frontend](https://quickstart-openshift-helpers-151-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-151-frontend.apps.silver.devops.gov.bc.ca/api)

chore(docs): add documentation for explanation of Crunchy Action using GHA

---

.github/workflows/.deployer.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-helpers-153-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-153-frontend.apps.silver.devops.gov.bc.ca/api)

fix: stop auto-applying Crunchy

---

.github/workflows/pr-open.yml

---
- [Frontend](https://quickstart-openshift-helpers-162-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-162-frontend.apps.silver.devops.gov.bc.ca/api)

chore: update crunchy action to latest version

---

renovate.json

---
- [Frontend](https://quickstart-openshift-helpers-164-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-164-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): renovate minimumReleaseAge=0

---

.github/workflows/.schema-spy.yml

https://github.com/bcgov/quickstart-openshift-helpers/security/code-scanning/25
---
- [Frontend](https://quickstart-openshift-helpers-178-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://quickstart-openshift-helpers-178-frontend.apps.silver.devops.gov.bc.ca/api)

chore(ci): workflow permissions for .schema-spu.yml
